
#GITHUB ACTIONS PIPELINE
name: Pipeline for Tests and Deploy Automation in Java

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

      # Service containers to run with `runner-job`
      services:
        # Label used to access the service container
        postgres:
          image: postgres
          env:
            POSTGRES_DB: msusers
            POSTGRES_PASSWORD: admin
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
          ports:
            - 5432:5432

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: |
#          mvn -B verify --file pom.xml
          mvn -B clean package --file pom.xml

#      - name: Build Docker image
#        run: docker build . -t msusers:latest